#!/usr/bin/env bash
#Display loop iteration with exceptions using while loop and condition statements
i=1
while [ $i -le 10 ]
do 
	(( i++ ))
	if [ $i == 5 ]
	then
		echo "bad luck"
	elif [ $i == 9 ]
	then 
		echo "good luck"
		continue
	else 
		echo "Best School"
	fi

done
