#!/usr/bin/env bash
#Dispay numbers 1 - 20 with exceptions using while loop and case statement
i=1
while [ $i -le 20 ]
do 
	echo $i
	((i++))
	
	case $i in

		5)
			echo -e "bad luck from China"
		
		;;

		10)
			echo -e "bad luck from Japan"
		;;

		18)
			echo -e "bad luck from Italy"
		;;
esac
done
