#!/usr/bin/env bash
# Displays time for 12 hours and 59 minutes
i=0
while [ $i -le 12 ]
do
	echo -n "Hour: $i"
	i=$(($i + 1))

	while [[ $i -le 59 ]]
	do
		if [[ $i -eq 59 ]]
		then
			continue 2
		fi

		echo -n $i
		((i++))
	done
done	
