#!/usr/bin/env bash
# Backup the original /etc/hosts file
cp /etc/hosts /etc/hosts.bak

# Modify the /etc/hosts file to set desired hostname resolutions
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts