#!/usr/bin/env bash
# This script generates a 4096-bit key pair named 'school' with passphrase 'betty'

# Variables
PRIVATE_KEY_NAME="school"
PASSPHRASE="betty"
KEY_SIZE=4096

# Generate RSA key pair
ssh-keygen -t rsa -b $KEY_SIZE -f $PRIVATE_KEY_NAME -N $PASSPHRASE